### ISSUE TITLE
Change naming to Matomo

### ISSUE THREAD

**Issue by Sebobo** [Flowpack/neos-matomo#14]
Piwik was renamed and the package should match that so people find 
what their looking for.

- [x] Transfer repository to flowpack
- [x] Fork back repo to old location to keep links to zip files working
- [x] Transfer packagist project
- [x] Rename repository to `neos-matomo`
- [x] Change all occurences of `piwik` to `matomo`
- [x] Add some notes to readme what happened

**Comment by koernchen02** [comment]
Is there allready a collaborative vendor-namespace present for neos packages?
I would suggest to use this opportunity to also change the vendor with the adjustments necessary for the matomo switch. I assume that moving this package to a more "neos-ish" namespace, might attract more people to use the package in the future. What do you think?

**Comment by Sebobo** [comment]
Hi @koernchen02,

I actually wanted to write you if it's ok to move it into Flowpack or Neos namespace :)
Wanted to check with the rest of the team which is better as the Analytics package is already in the Neos namespace.

If any one of those is fine for you I would try to take care of all of it next week during the Neos sprint.
This repository then needs to be moved or marked as deprecated. For that I might need your help then.

**Comment by koernchen02** [comment]
Hi @Sebobo,
thanks... That sounds great from our point of view, choose the namespace, that incorporates best in your naming strategy. Please do contact us (@sarahRehbock  or me) if you need any help or assistence.
We are looking forward to start contributing to the package in a new namespace later on ;)

Have a nice week!

**Comment by Sebobo** [comment]
Hi @koernchen02,

the transfer worked well and most requests are also redirected, but the links to the release zip downloads are broken now.

Can you fork this repo into your organization again, that would be the "official" way to fix this and still show where the new main repo is.

Thanks,
Sebastian

**Comment by koernchen02** [comment]
I just forked the repo "back"!
Have a nice week!

**Comment by Sebobo** [comment]
Hi @koernchen02,

thanks!
Another task :)
Can you abandon the project on packagist and if there is a way link it to the new project?

Thanks

**Comment by koernchen02** [comment]
"Abandoning" the package on packagist.org asks me for the _replacment package_'s name...
What should it be? (couldn't find it on packagist yet)
Since I'm not sure if I can set that replacement later on, I wanted to make that sure first before abandoning!

![screen shot 2018-04-09 at 12 03 12](https://user-images.githubusercontent.com/312900/38492037-004f907a-3bee-11e8-8abf-9a8d788fef9d.png)

**Comment by koernchen02** [comment]
I of course assume it will be `Flowpack/neos-matomo`, but I wanted to be 100% sure ;)

**Comment by koernchen02** [comment]
Ok now it's done...
Just refreshed packagist.org once more and the package was present...
`portachtzig/neos-piwik` now points to `flowpack/neos-matomo`:

![screen shot 2018-04-09 at 12 25 44](https://user-images.githubusercontent.com/312900/38493135-629a59ec-3bf1-11e8-9ae5-29643dedd3c3.png)

**Comment by Sebobo** [comment]
Awesome thanks. Piece by piece it comes together :)
