### ISSUE TITLE
The ViewHelper `<f:base>` could not be resolved.

### ISSUE THREAD

**Issue by jonnitto** [Flowpack/neos-matomo#23]
In Neos 4.0 the ViewHelper `<f:base>` is not available. Because of that, it is not possible to access `/neos/seo/matomo`

**Comment by Sebobo** [comment]
Can you checkout https://github.com/Flowpack/neos-matomo/pull/21, it includes also the fix for this

**Comment by jonnitto** [comment]
With #21, it'll work

**Comment by Sebobo** [comment]
Fixed in 3.0.1
