### ISSUE TITLE
no tracking code on website

### ISSUE THREAD

**Issue by stefkey** [Flowpack/neos-matomo#31]
Hi, there is no tracking code on my website. Only the code for the Matomo Tag Manager. All settings are fine. In the backend there found the IP and the version of Matomo 3.12. How can I debug?

**Comment by Sebobo** [comment]
Hi,

did you fully setup the tracking code on the Matomo side?
Just enabling the tag manager will not necessarily add the tracking code that the tag manager will then inject.

**Comment by stefkey** [comment]
yes?! 
<img width="1112" alt="Bildschirmfoto 2019-11-01 um 13 16 56" src="https://user-images.githubusercontent.com/3875195/68024474-7e975e80-fcaa-11e9-8458-fb4685e01123.png">

**Comment by Sebobo** [comment]
I mean adding the tracking as tag like described here https://matomo.org/docs/tag-manager/#1-configuring-a-tag

And for debugging you should use the Matomo tagmanager debug mode.

**Comment by stefkey** [comment]
I don't actually want to activate the tag manager. Isn't it possible without Tag Manager?

**Comment by Sebobo** [comment]
Ah ok, now I understand. Then just remove the Tag Manager ID.
The tracking code will then be rendered.

Usually when you use Tag Manager you wouldn‘t want the tracking code additionally.

**Comment by stefkey** [comment]
ahhhh ok. Sorry for this stupid thing. I have confused myself. There is another problem. My Neos doesn't recognize the Settings.Matomo.yaml in my site package, only the global Settings.Matomo.yaml is respected. Unfortunately I have only edited the Settings.Matomo.yaml in my site package so far. This was ignored and in the global settings.Matomo.yaml was always containerId: 'abcdef' :-(

Thank you for your patience.
