### ISSUE TITLE
Class 'Neos\Flow\Http\Uri' not found

### ISSUE THREAD

**Issue by pascualet** [Flowpack/neos-matomo#32]
Just installed as described (I'm using NEOS 5.01), configuration in Settings.yaml is done, but in backend at .../neos/seo/matomo I get the following error "Class 'Neos\Flow\Http\Uri' not found"

![screenshot_neos-matomo](https://user-images.githubusercontent.com/8255170/69350987-dc501280-0c7a-11ea-9f79-4b08abe46833.jpg)

**Comment by Sebobo** [comment]
@daniellienert did it work for you as you made the release for 5.0?

**Comment by daniellienert** [comment]
Might be, that I never tried the backend module 🤓
Can look into it tomorrow

**Comment by Sebobo** [comment]
Will check later. I'm currently updating my own site then I will see.
