### ISSUE TITLE
Probably wrong test for existing settings

### ISSUE THREAD

**Issue by PRGfx** [Flowpack/neos-matomo#35]
I haven't yet encountered an issue with this, but this seems wrong:
`!empty($this->settings['token_auth'] && !empty($this->settings['token_auth']))`
Found at https://github.com/Flowpack/neos-matomo/blob/97efb904d0e7049b2772ee7ef67bc8405276140e/Classes/Service/Reporting.php#L95 and https://github.com/Flowpack/neos-matomo/blob/97efb904d0e7049b2772ee7ef67bc8405276140e/Classes/Service/Reporting.php#L117

I would assume that it requires `protocol` and `idSite` as these are used in `buildApiCallUrl` called at both occurences, but I am not sure what it wanted to test for.

**Comment by Sebobo** [comment]
Yes the check is not fully correct but `token_auth` is also required. So it should rather check for host, protocol, idSite and tokenAuth,

Can you do a PR?
