### ISSUE TITLE
broken connection to the piwikserver slow down neos

### ISSUE THREAD

**Issue by stefkey** [Flowpack/neos-matomo#6]
Hi, sometimes I have broken connections to the piwik server. In the frontend there are no problems, but the backend are sometimes error messages, see below, and its very slowly. Is there no solution that the neos-piwik package ignore the broken connection after 1 second and goes on without piwik
-statistic for this page?

`Exception #1338906040 in line 183 of /var/www/neos/neos_2/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/TYPO3_Flow_Http_Client_Browser.php: cURL reported error code 28 with message "Operation timed out after 30001 milliseconds with 0 bytes received". Last requested URL was "https://piwik.xyz.de/pw/index.php?module=API&format=json&method=Actions.getOutlinks&date=last1&period=year&pageUrl=http%3A%2F%2Fwww.abc.de%2Fallgemeines.html&idSite=13&token_auth=xxxxxxxx&segment=pageUrl==http%3A%2F%2Fwww.abc.de%2Fallgemeines.html" (GET).`

**Comment by koernchen02** [comment]
That sounds reasonable, we will have a look at it as soon as possible...
We are also open for pull requests ;)

Best
Christian

**Comment by stefkey** [comment]
yeah, thanks! I think about it. Perhaps it is a good solution to get a button in the backend to turn on or off the statistic information in the backend. So that your package in this case only put the piwik tracking code in the frontend. Great and thanks, i wait for it.

**Comment by sualko** [comment]
Was this issue solved in the latest release?

**Comment by Sebobo** [comment]
@sualko don't think so. I just fixed some urgent configuration issues.

**Comment by Sebobo** [comment]
Hi @sualko,

first step would be to not mark it as WIP anymore, finish any open tasks you still have in the change and assign me for reviewing the final change.
Then I will check it out :)
